card_data = [{'name': 'The Fool',
  'image': 'images/00-TheFool.png',
  'upright': 'New beginnings, freedom, and adventure',
  'reversed': 'Recklessness, fear of change, and poor judgment'},
 {'name': 'The Magician',
  'image': 'images/01-TheMagician.png',
  'upright': 'Skill, confidence, and manifestation',
  'reversed': 'Manipulation, wasted potential, and lack of direction'},
 {'name': 'The High Priestess',
  'image': 'images/02-TheHighPriestess.png',
  'upright': 'Intuition, mystery, and inner knowledge',
  'reversed': 'Ignoring intuition, secrets, and confusion'},
 {'name': 'The Empress',
  'image': 'images/03-TheEmpress.png',
  'upright': 'Creativity, abundance, and nurturing',
  'reversed': 'Creative blocks, dependence, and neglecting yourself'},
 {'name': 'The Emperor',
  'image': 'images/04-TheEmperor.png',
  'upright': 'Structure, stability, and leadership',
  'reversed': 'Control, stubbornness, and misuse of power'},
 {'name': 'The Hierophant',
  'image': 'images/05-TheHierophant.png',
  'upright': 'Tradition, learning, and spiritual guidance',
  'reversed': 'Rebellion, personal beliefs, and rejecting tradition'},
 {'name': 'The Lovers',
  'image': 'images/06-TheLovers.png',
  'upright': 'Love, harmony, and meaningful choices',
  'reversed': 'Disharmony, imbalance, and conflicting values'},
 {'name': 'The Chariot',
  'image': 'images/07-TheChariot.png',
  'upright': 'Determination, control, and forward movement',
  'reversed': 'Lack of direction, aggression, and losing control'},
 {'name': 'Strength',
  'image': 'images/08-Strength.png',
  'upright': 'Courage, patience, and inner strength',
  'reversed': 'Self-doubt, insecurity, and emotional weakness'},
 {'name': 'The Hermit',
  'image': 'images/09-TheHermit.png',
  'upright': 'Reflection, solitude, and inner guidance',
  'reversed': 'Isolation, loneliness, and avoiding reflection'},
 {'name': 'Wheel of Fortune',
  'image': 'images/10-WheelOfFortune.png',
  'upright': 'Change, luck, and turning points',
  'reversed': 'Bad luck, resistance to change, and setbacks'},
 {'name': 'Justice',
  'image': 'images/11-Justice.png',
  'upright': 'Fairness, truth, and accountability',
  'reversed': 'Dishonesty, unfairness, and avoiding responsibility'},
 {'name': 'The Hanged Man',
  'image': 'images/12-TheHangedMan.png',
  'upright': 'Surrender, patience, and a new perspective',
  'reversed': 'Delays, resistance, and feeling stuck'},
 {'name': 'Death',
  'image': 'images/13-Death.png',
  'upright': 'Endings, transformation, and new beginnings',
  'reversed': 'Fear of change, stagnation, and holding on'},
 {'name': 'Temperance',
  'image': 'images/14-Temperance.png',
  'upright': 'Balance, patience, and moderation',
  'reversed': 'Excess, imbalance, and lack of harmony'},
 {'name': 'The Devil',
  'image': 'images/15-TheDevil.png',
  'upright': 'Attachment, temptation, and unhealthy patterns',
  'reversed': 'Freedom, awareness, and breaking harmful cycles'},
 {'name': 'The Tower',
  'image': 'images/16-TheTower.png',
  'upright': 'Sudden change, disruption, and revelation',
  'reversed': 'Avoiding change, fear, and delayed disaster'},
 {'name': 'The Star',
  'image': 'images/17-TheStar.png',
  'upright': 'Hope, healing, and inspiration',
  'reversed': 'Discouragement, doubt, and loss of faith'},
 {'name': 'The Moon',
  'image': 'images/18-TheMoon.png',
  'upright': 'Illusion, intuition, and uncertainty',
  'reversed': 'Clarity, released fear, and hidden truths revealed'},
 {'name': 'The Sun',
  'image': 'images/19-TheSun.png',
  'upright': 'Joy, success, and confidence',
  'reversed': 'Temporary sadness, low confidence, and delayed success'},
 {'name': 'Judgement',
  'image': 'images/20-Judgement.png',
  'upright': 'Awakening, reflection, and important decisions',
  'reversed': 'Self-doubt, avoidance, and refusing a lesson'},
 {'name': 'The World',
  'image': 'images/21-TheWorld.png',
  'upright': 'Completion, achievement, and fulfillment',
  'reversed': 'Unfinished business, delays, and lack of closure'},
 {'name': 'Ace of Wands',
  'image': 'images/Wands01.png',
  'upright': 'Inspiration, passion, and a new opportunity',
  'reversed': 'Delays, low energy, and lack of inspiration'},
 {'name': 'Two of Wands',
  'image': 'images/Wands02.png',
  'upright': 'Planning, decisions, and future possibilities',
  'reversed': 'Fear of the unknown, poor planning, and hesitation'},
 {'name': 'Three of Wands',
  'image': 'images/Wands03.png',
  'upright': 'Expansion, progress, and looking ahead',
  'reversed': 'Delays, obstacles, and limited thinking'},
 {'name': 'Four of Wands',
  'image': 'images/Wands04.png',
  'upright': 'Celebration, community, and stability',
  'reversed': 'Conflict at home, instability, and canceled celebration'},
 {'name': 'Five of Wands',
  'image': 'images/Wands05.png',
  'upright': 'Competition, conflict, and tension',
  'reversed': 'Avoiding conflict, compromise, and inner tension'},
 {'name': 'Six of Wands',
  'image': 'images/Wands06.png',
  'upright': 'Victory, recognition, and confidence',
  'reversed': 'Self-doubt, lack of recognition, and pride'},
 {'name': 'Seven of Wands',
  'image': 'images/Wands07.png',
  'upright': 'Courage, defense, and standing your ground',
  'reversed': 'Exhaustion, giving up, and feeling overwhelmed'},
 {'name': 'Eight of Wands',
  'image': 'images/Wands08.png',
  'upright': 'Speed, movement, and rapid progress',
  'reversed': 'Delays, frustration, and miscommunication'},
 {'name': 'Nine of Wands',
  'image': 'images/Wands09.png',
  'upright': 'Resilience, persistence, and boundaries',
  'reversed': 'Exhaustion, defensiveness, and giving up'},
 {'name': 'Ten of Wands',
  'image': 'images/Wands10.png',
  'upright': 'Responsibility, burden, and hard work',
  'reversed': 'Burnout, releasing burdens, and asking for help'},
 {'name': 'Page of Wands',
  'image': 'images/Wands11.png',
  'upright': 'Curiosity, enthusiasm, and discovery',
  'reversed': 'Lack of direction, impatience, and scattered energy'},
 {'name': 'Knight of Wands',
  'image': 'images/Wands12.png',
  'upright': 'Adventure, confidence, and energetic action',
  'reversed': 'Recklessness, anger, and impulsiveness'},
 {'name': 'Queen of Wands',
  'image': 'images/Wands13.png',
  'upright': 'Confidence, independence, and warmth',
  'reversed': 'Jealousy, insecurity, and demanding behavior'},
 {'name': 'King of Wands',
  'image': 'images/Wands14.png',
  'upright': 'Leadership, vision, and bold action',
  'reversed': 'Arrogance, impulsiveness, and unrealistic expectations'},
 {'name': 'Ace of Cups',
  'image': 'images/Cups01.png',
  'upright': 'Love, compassion, and emotional beginnings',
  'reversed': 'Emotional blocks, emptiness, and suppressed feelings'},
 {'name': 'Two of Cups',
  'image': 'images/Cups02.png',
  'upright': 'Partnership, connection, and mutual attraction',
  'reversed': 'Separation, imbalance, and poor communication'},
 {'name': 'Three of Cups',
  'image': 'images/Cups03.png',
  'upright': 'Friendship, celebration, and community',
  'reversed': 'Gossip, overindulgence, and social conflict'},
 {'name': 'Four of Cups',
  'image': 'images/Cups04.png',
  'upright': 'Contemplation, apathy, and reevaluation',
  'reversed': 'New awareness, motivation, and accepting opportunities'},
 {'name': 'Five of Cups',
  'image': 'images/Cups05.png',
  'upright': 'Loss, grief, and disappointment',
  'reversed': 'Healing, acceptance, and moving forward'},
 {'name': 'Six of Cups',
  'image': 'images/Cups06.png',
  'upright': 'Nostalgia, innocence, and happy memories',
  'reversed': 'Living in the past, immaturity, and unrealistic memories'},
 {'name': 'Seven of Cups',
  'image': 'images/Cups07.png',
  'upright': 'Choices, imagination, and many possibilities',
  'reversed': 'Clarity, commitment, and narrowing your options'},
 {'name': 'Eight of Cups',
  'image': 'images/Cups08.png',
  'upright': 'Walking away, searching, and emotional growth',
  'reversed': 'Fear of leaving, avoidance, and returning to the past'},
 {'name': 'Nine of Cups',
  'image': 'images/Cups09.png',
  'upright': 'Satisfaction, gratitude, and wishes fulfilled',
  'reversed': 'Dissatisfaction, excess, and unmet expectations'},
 {'name': 'Ten of Cups',
  'image': 'images/Cups10.png',
  'upright': 'Harmony, family, and emotional fulfillment',
  'reversed': 'Family conflict, broken connection, and disharmony'},
 {'name': 'Page of Cups',
  'image': 'images/Cups11.png',
  'upright': 'Creativity, sensitivity, and emotional messages',
  'reversed': 'Emotional immaturity, insecurity, and creative blocks'},
 {'name': 'Knight of Cups',
  'image': 'images/Cups12.png',
  'upright': 'Romance, charm, and following your heart',
  'reversed': 'Moodiness, disappointment, and unrealistic expectations'},
 {'name': 'Queen of Cups',
  'image': 'images/Cups13.png',
  'upright': 'Compassion, intuition, and emotional support',
  'reversed': 'Emotional dependence, insecurity, and poor boundaries'},
 {'name': 'King of Cups',
  'image': 'images/Cups14.png',
  'upright': 'Emotional balance, wisdom, and calm leadership',
  'reversed': 'Emotional manipulation, moodiness, and repression'},
 {'name': 'Ace of Swords',
  'image': 'images/Swords01.png',
  'upright': 'Clarity, truth, and a new idea',
  'reversed': 'Confusion, poor judgment, and lack of clarity'},
 {'name': 'Two of Swords',
  'image': 'images/Swords02.png',
  'upright': 'Indecision, difficult choices, and avoidance',
  'reversed': 'Information overload, anxiety, and a forced decision'},
 {'name': 'Three of Swords',
  'image': 'images/Swords03.png',
  'upright': 'Heartbreak, sorrow, and painful truth',
  'reversed': 'Healing, forgiveness, and releasing pain'},
 {'name': 'Four of Swords',
  'image': 'images/Swords04.png',
  'upright': 'Rest, recovery, and reflection',
  'reversed': 'Burnout, restlessness, and returning too soon'},
 {'name': 'Five of Swords',
  'image': 'images/Swords05.png',
  'upright': 'Conflict, tension, and winning at a cost',
  'reversed': 'Reconciliation, regret, and ending conflict'},
 {'name': 'Six of Swords',
  'image': 'images/Swords06.png',
  'upright': 'Transition, healing, and moving forward',
  'reversed': 'Resistance to change, emotional baggage, and feeling stuck'},
 {'name': 'Seven of Swords',
  'image': 'images/Swords07.png',
  'upright': 'Strategy, secrecy, and acting alone',
  'reversed': 'Confession, exposure, and self-deception'},
 {'name': 'Eight of Swords',
  'image': 'images/Swords08.png',
  'upright': 'Restriction, fear, and feeling trapped',
  'reversed': 'Freedom, new perspective, and taking control'},
 {'name': 'Nine of Swords',
  'image': 'images/Swords09.png',
  'upright': 'Anxiety, worry, and sleeplessness',
  'reversed': 'Recovery, hope, and releasing fear'},
 {'name': 'Ten of Swords',
  'image': 'images/Swords10.png',
  'upright': 'Painful endings, betrayal, and rock bottom',
  'reversed': 'Recovery, survival, and resisting an ending'},
 {'name': 'Page of Swords',
  'image': 'images/Swords11.png',
  'upright': 'Curiosity, communication, and new ideas',
  'reversed': 'Gossip, defensiveness, and scattered thinking'},
 {'name': 'Knight of Swords',
  'image': 'images/Swords12.png',
  'upright': 'Ambition, action, and determination',
  'reversed': 'Aggression, impatience, and reckless decisions'},
 {'name': 'Queen of Swords',
  'image': 'images/Swords13.png',
  'upright': 'Independence, honesty, and clear judgment',
  'reversed': 'Bitterness, harshness, and emotional coldness'},
 {'name': 'King of Swords',
  'image': 'images/Swords14.png',
  'upright': 'Logic, authority, and intellectual clarity',
  'reversed': 'Manipulation, cruelty, and misuse of power'},
 {'name': 'Ace of Pentacles',
  'image': 'images/Pentacles01.png',
  'upright': 'Opportunity, stability, and financial beginnings',
  'reversed': 'Missed opportunities, poor planning, and instability'},
 {'name': 'Two of Pentacles',
  'image': 'images/Pentacles02.png',
  'upright': 'Balance, adaptability, and managing priorities',
  'reversed': 'Overwhelm, disorganization, and imbalance'},
 {'name': 'Three of Pentacles',
  'image': 'images/Pentacles03.png',
  'upright': 'Teamwork, learning, and skilled work',
  'reversed': 'Poor teamwork, low quality, and lack of effort'},
 {'name': 'Four of Pentacles',
  'image': 'images/Pentacles04.png',
  'upright': 'Security, saving, and holding on',
  'reversed': 'Greed, overspending, and releasing control'},
 {'name': 'Five of Pentacles',
  'image': 'images/Pentacles05.png',
  'upright': 'Hardship, isolation, and financial struggle',
  'reversed': 'Recovery, support, and improving circumstances'},
 {'name': 'Six of Pentacles',
  'image': 'images/Pentacles06.png',
  'upright': 'Generosity, support, and balanced giving',
  'reversed': 'Debt, unequal support, and strings attached'},
 {'name': 'Seven of Pentacles',
  'image': 'images/Pentacles07.png',
  'upright': 'Patience, progress, and long-term investment',
  'reversed': 'Impatience, wasted effort, and little reward'},
 {'name': 'Eight of Pentacles',
  'image': 'images/Pentacles08.png',
  'upright': 'Practice, dedication, and developing skill',
  'reversed': 'Perfectionism, poor quality, and lack of focus'},
 {'name': 'Nine of Pentacles',
  'image': 'images/Pentacles09.png',
  'upright': 'Independence, comfort, and earned success',
  'reversed': 'Dependence, overspending, and false success'},
 {'name': 'Ten of Pentacles',
  'image': 'images/Pentacles10.png',
  'upright': 'Legacy, wealth, and long-term stability',
  'reversed': 'Family conflict, financial loss, and unstable foundations'},
 {'name': 'Page of Pentacles',
  'image': 'images/Pentacles11.png',
  'upright': 'Learning, ambition, and practical opportunities',
  'reversed': 'Procrastination, lack of progress, and poor planning'},
 {'name': 'Knight of Pentacles',
  'image': 'images/Pentacles12.png',
  'upright': 'Reliability, patience, and steady progress',
  'reversed': 'Stubbornness, boredom, and lack of progress'},
 {'name': 'Queen of Pentacles',
  'image': 'images/Pentacles13.png',
  'upright': 'Practicality, comfort, and nurturing support',
  'reversed': 'Self-neglect, jealousy, and work-life imbalance'},
 {'name': 'King of Pentacles',
  'image': 'images/Pentacles14.png',
  'upright': 'Abundance, security, and dependable leadership',
  'reversed': 'Greed, materialism, and poor financial judgment'}]